name: fiwork
description: A freelance networking application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_analytics: ^9.1.10
  file_picker: ^5.2.0
  firebase_core: ^1.19.1
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.1
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.1.0
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  webview_flutter: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
